### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by kishaningithub** [SceneView/sceneview-flutter#6]
The release that is present in flutter pub viz 0.0.1 seems to be very old.

For example if you see the `SceneView` class, the `onViewCreated` function does not exist in the published version (screenshot below)

## Published version

<img width="800" alt="image" src="https://github.com/SceneView/sceneview-flutter/assets/763760/13fefbc4-92f3-488a-9dd2-814e30cf9f24">

## Latest one in main branch

https://github.com/SceneView/sceneview-flutter/blob/66b458d59f0f3669d65d08ba3745b7f26790b21e/lib/scene_view.dart#LL13C2-L13C2

**Comment by giandifra** [comment]
There was a problem that has locked me to continue! #3
